### ISSUE TITLE
Missing CI for Android app

### ISSUE THREAD

**Issue by platisd** [DIT113-V22/group-17#24]

**Comment by ErgiGU** [comment]
@platisd just finished implementing this(it's in the main2 branch, we'll merge it shortly)

**Comment by platisd** [comment]
What you merged clearly doesn't work, so this is still open.

**Comment by ErgiGU** [comment]
this is weird, it was passing before

**Comment by ErgiGU** [comment]
@platisd  It's finally implemented, so i'm closing the issue
