### ISSUE TITLE
Registration, Login and Personal Info Page[Out of Scope]

### ISSUE THREAD

**Issue by ErgiGU** [DIT113-V22/group-17#34]
**User Story**

As a user I’d like to be able to log into the app and save my information about the car such as its registration number, set speed and travelled distance.

**Acceptance Criteria:**

- There is a login, registration and personal information screen in the app.
- The login, registration and personal information that is inputted is stored appropriately.

**Comment by Yajiri** [comment]
This is outside our scope so it won't be done in this project. (but I might work on it over summer (for fun)).

**Comment by ErgiGU** [comment]
Alright then, I'm closing the issue
